version: '3.8'

services:
  backend:
    build: ./backend
    container_name: adonis_backend
    restart: always
    ports:
      - "3333:3333"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
    depends_on:
      - database

  frontend:
    build: ./frontend
    container_name: nuxt_frontend
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend

  database:
    image: mariadb:10.6
    container_name: mariadb
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: adonis
      MYSQL_USER: adonis
      MYSQL_PASSWORD: rootpassword
    volumes:
      - mariadb_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
    depends_on:
      - database

volumes:
  mariadb_data:
